services:

  backend:
    build:
      context: ./backend
    container_name: acai_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: acai_frontend
    ports:
      - "8080:80"
    restart: unless-stopped
