services:

  backend:
    build:
      context: ./backend
    container_name: acai_backend
    ports:
      - "5000:5000"
    volumes:
      - ./db:/db
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: acai_frontend
    ports:
      - "8080:80"   # cliente
      - "8081:81"   # gestor
      - "8082:82"   # admin
    restart: unless-stopped

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: acai_sqlite_web
    ports:
      - "8083:8080"
    volumes:
      - ./db:/data
    command: sqlite_web --host 0.0.0.0 /data/pedidos.db
    restart: unless-stopped
