services:

  backend:
    build:
      context: ./backend
    container_name: acai_backend
    ports:
      - "5000:5000"
    volumes:
      - ./db:/db
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: acai_frontend
    ports:
      - "8080:80"   # cliente
      - "8081:81"   # gestor
    restart: unless-stopped
