services:
  - type: web
    name: acai-express-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: TZ
        value: America/Sao_Paulo
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: MP_PUBLIC_KEY
        sync: false
      - key: OWNER_USUARIO
        sync: false
      - key: OWNER_SENHA
        sync: false
